import type { Opportunity } from "@/lib/opportunitySchema";

export const routeOpportunities: Opportunity[] = [
  {
    id: "plant-based-cooking-class",
    title: "Plant-Based Cooking Class",
    sourceUrl: null,
    sourceName: "Pathoro mock seed",
    sourceType: "mock_seed",
    city: "Austin",
    state: "TX",
    locationLabel: "East Austin",
    dateLabel: "Sat, 10:00 AM",
    costLabel: "$35",
    hostName: "Greenhouse Kitchen Studio",
    description: "Try the change in a real setting, guided and hands-on.",
    routeId: "real-openings",
    opportunityType: "Class / Opening",
    whoItIsFor: "Beginners curious about plant-forward cooking",
    pathItSupports: "Become vegetarian",
    whatItMayOpenNext: "A recurring cooking group or a nutrition coach intro call",
    effortLevel: "Low",
    frictionLevel: "Low",
    trustLevel: "Medium",
    status: "live",
    href: "/opportunity/plant-based-cooking-class",
    relevanceKeywords: ["vegetarian", "vegan", "plant-based", "plant based", "cooking", "food", "nutrition", "diet", "health"],
  },
  {
    id: "intro-ceramics-night",
    title: "Intro Ceramics Night",
    sourceUrl: null,
    sourceName: "Pathoro mock seed",
    sourceType: "mock_seed",
    city: "Austin",
    state: "TX",
    locationLabel: "South Austin",
    dateLabel: "Thu, 6:30 PM",
    costLabel: "$40",
    hostName: "Clay Pot Studio",
    description: "A one-night, no-experience-needed studio session to try something with your hands.",
    routeId: "real-openings",
    opportunityType: "Class / Opening",
    whoItIsFor: "Anyone wanting a low-pressure creative outlet",
    pathItSupports: "Start a creative project",
    whatItMayOpenNext: "A recurring studio membership",
    effortLevel: "Low",
    frictionLevel: "Medium",
    trustLevel: "Medium",
    status: "preview",
    relevanceKeywords: ["ceramics", "pottery", "creative", "art", "craft", "hands-on", "hobby"],
  },
  {
    id: "beginner-vegetarian-meetup",
    title: "Beginner Vegetarian Meetup",
    sourceUrl: null,
    sourceName: "Pathoro mock seed",
    sourceType: "mock_seed",
    city: "Austin",
    state: "TX",
    locationLabel: "Central Austin",
    dateLabel: "Tue, 7:00 PM",
    costLabel: "Free",
    hostName: "Austin Plant Curious",
    description: "Be around people already living this, so it feels normal, not novel.",
    routeId: "community",
    opportunityType: "Group / Community",
    whoItIsFor: "People early in changing how they eat",
    pathItSupports: "Change a habit / lifestyle",
    whatItMayOpenNext: "A standing weekly potluck group",
    effortLevel: "Low",
    frictionLevel: "Low",
    trustLevel: "Medium",
    status: "preview",
    relevanceKeywords: ["vegetarian", "vegan", "plant-based", "plant based", "food", "health", "nutrition", "diet"],
  },
  {
    id: "running-walking-group",
    title: "Local Running / Walking Group",
    sourceUrl: null,
    sourceName: "Pathoro mock seed",
    sourceType: "mock_seed",
    city: "Austin",
    state: "TX",
    locationLabel: "Lady Bird Lake Trail",
    dateLabel: "Sat, 8:00 AM",
    costLabel: "Free",
    hostName: "Town Lake Pacers",
    description: "A standing, all-paces group so moving with others feels normal, not intimidating.",
    routeId: "community",
    opportunityType: "Group / Community",
    whoItIsFor: "Beginners and returners at any pace",
    pathItSupports: "Build a movement habit",
    whatItMayOpenNext: "A training group with a shared goal race",
    effortLevel: "Medium",
    frictionLevel: "Low",
    trustLevel: "Medium",
    status: "preview",
    relevanceKeywords: ["run", "running", "walk", "walking", "fitness", "exercise", "movement", "health"],
  },
  {
    id: "career-change-workshop",
    title: "Career-Change Workshop",
    sourceUrl: null,
    sourceName: "Pathoro mock seed",
    sourceType: "mock_seed",
    city: "Austin",
    state: "TX",
    locationLabel: "North Austin",
    dateLabel: "Wed, 6:00 PM",
    costLabel: "$15",
    hostName: "Austin Career Collective",
    description: "Map what a real transition would actually require before you commit to it.",
    routeId: "requirements",
    opportunityType: "Planning / Requirements",
    whoItIsFor: "People seriously considering a career change",
    pathItSupports: "Start a new career",
    whatItMayOpenNext: "1:1 career coaching or a peer accountability group",
    effortLevel: "Medium",
    frictionLevel: "Medium",
    trustLevel: "Medium",
    status: "preview",
    relevanceKeywords: ["career", "job", "work", "profession", "transition"],
  },
  {
    id: "library-skill-workshop",
    title: "Public Library Skill Workshop",
    sourceUrl: null,
    sourceName: "Pathoro mock seed",
    sourceType: "mock_seed",
    city: "Austin",
    state: "TX",
    locationLabel: "Austin Central Library",
    dateLabel: "Sat, 1:00 PM",
    costLabel: "Free",
    hostName: "Austin Public Library",
    description: "Free, low-stakes, and a good way to learn exactly what you're missing before diving in.",
    routeId: "requirements",
    opportunityType: "Planning / Requirements",
    whoItIsFor: "Anyone wanting a low-cost way to build a foundational skill",
    pathItSupports: "Build a skill you want to build",
    whatItMayOpenNext: "A follow-up series or a practice group",
    effortLevel: "Low",
    frictionLevel: "Low",
    trustLevel: "High",
    status: "preview",
  },
  {
    id: "community-garden-volunteer-day",
    title: "Community Garden Volunteer Day",
    sourceUrl: null,
    sourceName: "Pathoro mock seed",
    sourceType: "mock_seed",
    city: "Austin",
    state: "TX",
    locationLabel: "Bouldin Creek Community Garden",
    dateLabel: "Sun, 9:00 AM",
    costLabel: "Free",
    hostName: "Bouldin Creek Community Garden",
    description: "A single low-pressure morning to see if this is something you actually enjoy.",
    relevanceKeywords: ["garden", "gardening", "vegetarian", "vegan", "plant-based", "plant based", "food", "health", "habit", "lifestyle", "environment"],
    routeId: "try-it",
    opportunityType: "Small Trial",
    whoItIsFor: "Anyone curious but not ready to commit",
    pathItSupports: "Change a habit / lifestyle",
    whatItMayOpenNext: "A recurring garden plot or volunteer role",
    effortLevel: "Low",
    frictionLevel: "Low",
    trustLevel: "Medium",
    status: "preview",
  },
  {
    id: "coworking-founder-meetup",
    title: "Coworking Founder Meetup",
    sourceUrl: null,
    sourceName: "Pathoro mock seed",
    sourceType: "mock_seed",
    city: "Austin",
    state: "TX",
    locationLabel: "East Austin Coworking Collective",
    dateLabel: "Thu, 5:30 PM",
    costLabel: "Free",
    hostName: "East Austin Coworking Collective",
    description: "Talk with people already doing the thing you're considering, in an informal setting.",
    routeId: "people",
    opportunityType: "Person / Conversation",
    whoItIsFor: "People exploring a change and wanting to hear how others made it real",
    pathItSupports: "Start a new career",
    relevanceKeywords: ["career", "job", "business", "founder", "entrepreneur", "startup", "professional", "work"],
    whatItMayOpenNext: "A one-on-one coffee chat or informal mentorship",
    effortLevel: "Low",
    frictionLevel: "Low",
    trustLevel: "Medium",
    status: "preview",
  },
  {
    id: "hvac-apprenticeship-info-session",
    title: "HVAC Apprenticeship Info Session",
    sourceUrl: null,
    sourceName: "Pathoro example",
    sourceType: "mock_seed",
    city: "Austin",
    state: "TX",
    locationLabel: "Austin Community College — HVAC Program",
    dateLabel: "Thu, 6:00 PM",
    costLabel: "Free",
    hostName: "Austin Community College HVAC Program",
    description:
      "A local info session for people considering HVAC apprenticeships — meet current apprentices, ask about union vs. non-union paths, and learn what programs actually require to get started.",
    routeId: "real-openings",
    opportunityType: "Info session / Access point",
    whoItIsFor: "Anyone exploring HVAC as a trade, with or without experience",
    pathItSupports: "Become an HVAC technician",
    whatItMayOpenNext: "An apprenticeship application or a connection to a trade school program",
    effortLevel: "Low",
    frictionLevel: "Low",
    trustLevel: "Medium",
    status: "live",
    href: "/opportunity/hvac-apprenticeship-info-session",
    relevanceKeywords: ["hvac", "hvac technician", "heating", "cooling", "trade", "apprenticeship", "trades"],
  },
  {
    id: "wedding-photographer-assistant-opportunity",
    title: "Wedding Photographer Assistant Opportunity",
    sourceUrl: null,
    sourceName: "Pathoro example",
    sourceType: "mock_seed",
    city: "Austin",
    state: "TX",
    locationLabel: "Austin, TX (on-location at weddings)",
    dateLabel: "Ongoing, weekend availability needed",
    costLabel: "Paid per shoot",
    hostName: "Independent wedding photographer",
    description:
      "A working wedding photographer is looking for a second shooter / assistant to learn the wedding-day flow, help with gear, and get real experience before booking solo clients.",
    routeId: "real-openings",
    opportunityType: "Assistant role / Access point",
    whoItIsFor: "Photographers with basic skills looking for their first real wedding experience",
    pathItSupports: "Become a wedding photographer",
    whatItMayOpenNext: "Referrals, a second-shooter reputation, or a path to freelance wedding work",
    effortLevel: "Medium",
    frictionLevel: "Medium",
    trustLevel: "Medium",
    status: "live",
    href: "/opportunity/wedding-photographer-assistant-opportunity",
    relevanceKeywords: ["wedding photographer", "photographer", "photography", "creative", "assistant", "second shooter"],
  },
];

export function getOpportunitiesForRoute(routeId: string): Opportunity[] {
  return routeOpportunities.filter((o) => o.routeId === routeId);
}
