import type { Opportunity } from "@/lib/opportunitySchema";

export const routeOpportunities: Opportunity[] = [
  {
    id: "plant-based-cooking-class",
    title: "Plant-Based Cooking Class",
    sourceUrl: null,
    sourceName: "Pathoro mock seed",
    sourceType: "mock_seed",
    city: "Austin",
    state: "TX",
    locationLabel: "East Austin",
    dateLabel: "Sat, 10:00 AM",
    costLabel: "$35",
    hostName: "Greenhouse Kitchen Studio",
    description: "Try the change in a real setting, guided and hands-on.",
    routeId: "real-openings",
    opportunityType: "Class / Event",
    whoItIsFor: "Beginners curious about plant-forward cooking",
    pathItSupports: "Change a habit / lifestyle",
    whatItMayOpenNext: "A recurring cooking group or a nutrition coach intro call",
    effortLevel: "Low",
    frictionLevel: "Low",
    trustLevel: "Medium",
    status: "preview",
    href: "/opportunity/plant-based-cooking-class",
  },
  {
    id: "intro-ceramics-night",
    title: "Intro Ceramics Night",
    sourceUrl: null,
    sourceName: "Pathoro mock seed",
    sourceType: "mock_seed",
    city: "Austin",
    state: "TX",
    locationLabel: "South Austin",
    dateLabel: "Thu, 6:30 PM",
    costLabel: "$40",
    hostName: "Clay Pot Studio",
    description: "A one-night, no-experience-needed studio session to try something with your hands.",
    routeId: "real-openings",
    opportunityType: "Class / Event",
    whoItIsFor: "Anyone wanting a low-pressure creative outlet",
    pathItSupports: "Start a creative project",
    whatItMayOpenNext: "A recurring studio membership",
    effortLevel: "Low",
    frictionLevel: "Medium",
    trustLevel: "Medium",
    status: "preview",
  },
  {
    id: "beginner-vegetarian-meetup",
    title: "Beginner Vegetarian Meetup",
    sourceUrl: null,
    sourceName: "Pathoro mock seed",
    sourceType: "mock_seed",
    city: "Austin",
    state: "TX",
    locationLabel: "Central Austin",
    dateLabel: "Tue, 7:00 PM",
    costLabel: "Free",
    hostName: "Austin Plant Curious",
    description: "Be around people already living this, so it feels normal, not novel.",
    routeId: "community",
    opportunityType: "Group / Community",
    whoItIsFor: "People early in changing how they eat",
    pathItSupports: "Change a habit / lifestyle",
    whatItMayOpenNext: "A standing weekly potluck group",
    effortLevel: "Low",
    frictionLevel: "Low",
    trustLevel: "Medium",
    status: "preview",
  },
  {
    id: "running-walking-group",
    title: "Local Running / Walking Group",
    sourceUrl: null,
    sourceName: "Pathoro mock seed",
    sourceType: "mock_seed",
    city: "Austin",
    state: "TX",
    locationLabel: "Lady Bird Lake Trail",
    dateLabel: "Sat, 8:00 AM",
    costLabel: "Free",
    hostName: "Town Lake Pacers",
    description: "A standing, all-paces group so moving with others feels normal, not intimidating.",
    routeId: "community",
    opportunityType: "Group / Community",
    whoItIsFor: "Beginners and returners at any pace",
    pathItSupports: "Build a movement habit",
    whatItMayOpenNext: "A training group with a shared goal race",
    effortLevel: "Medium",
    frictionLevel: "Low",
    trustLevel: "Medium",
    status: "preview",
  },
  {
    id: "career-change-workshop",
    title: "Career-Change Workshop",
    sourceUrl: null,
    sourceName: "Pathoro mock seed",
    sourceType: "mock_seed",
    city: "Austin",
    state: "TX",
    locationLabel: "North Austin",
    dateLabel: "Wed, 6:00 PM",
    costLabel: "$15",
    hostName: "Austin Career Collective",
    description: "Map what a real transition would actually require before you commit to it.",
    routeId: "requirements",
    opportunityType: "Planning / Requirements",
    whoItIsFor: "People seriously considering a career change",
    pathItSupports: "Start a new career",
    whatItMayOpenNext: "1:1 career coaching or a peer accountability group",
    effortLevel: "Medium",
    frictionLevel: "Medium",
    trustLevel: "Medium",
    status: "preview",
  },
  {
    id: "library-skill-workshop",
    title: "Public Library Skill Workshop",
    sourceUrl: null,
    sourceName: "Pathoro mock seed",
    sourceType: "mock_seed",
    city: "Austin",
    state: "TX",
    locationLabel: "Austin Central Library",
    dateLabel: "Sat, 1:00 PM",
    costLabel: "Free",
    hostName: "Austin Public Library",
    description: "Free, low-stakes, and a good way to learn exactly what you're missing before diving in.",
    routeId: "requirements",
    opportunityType: "Planning / Requirements",
    whoItIsFor: "Anyone wanting a low-cost way to build a foundational skill",
    pathItSupports: "Build a skill you want to build",
    whatItMayOpenNext: "A follow-up series or a practice group",
    effortLevel: "Low",
    frictionLevel: "Low",
    trustLevel: "High",
    status: "preview",
  },
  {
    id: "community-garden-volunteer-day",
    title: "Community Garden Volunteer Day",
    sourceUrl: null,
    sourceName: "Pathoro mock seed",
    sourceType: "mock_seed",
    city: "Austin",
    state: "TX",
    locationLabel: "Bouldin Creek Community Garden",
    dateLabel: "Sun, 9:00 AM",
    costLabel: "Free",
    hostName: "Bouldin Creek Community Garden",
    description: "A single low-pressure morning to see if this is something you actually enjoy.",
    routeId: "try-it",
    opportunityType: "Small Trial",
    whoItIsFor: "Anyone curious but not ready to commit",
    pathItSupports: "Change a habit / lifestyle",
    whatItMayOpenNext: "A recurring garden plot or volunteer role",
    effortLevel: "Low",
    frictionLevel: "Low",
    trustLevel: "Medium",
    status: "preview",
  },
  {
    id: "coworking-founder-meetup",
    title: "Coworking Founder Meetup",
    sourceUrl: null,
    sourceName: "Pathoro mock seed",
    sourceType: "mock_seed",
    city: "Austin",
    state: "TX",
    locationLabel: "East Austin Coworking Collective",
    dateLabel: "Thu, 5:30 PM",
    costLabel: "Free",
    hostName: "East Austin Coworking Collective",
    description: "Talk with people already doing the thing you're considering, in an informal setting.",
    routeId: "people",
    opportunityType: "Person / Conversation",
    whoItIsFor: "People exploring a change and wanting to hear how others made it real",
    pathItSupports: "Start a new career",
    whatItMayOpenNext: "A one-on-one coffee chat or informal mentorship",
    effortLevel: "Low",
    frictionLevel: "Low",
    trustLevel: "Medium",
    status: "preview",
  },
];

export function getOpportunitiesForRoute(routeId: string): Opportunity[] {
  return routeOpportunities.filter((o) => o.routeId === routeId);
}
